---
title: "R Notebook"
output: github_document
---


# Working with COVID-19 Data in R
## Liam Osler 

Clone the global COVID-19 Data from the github repository:

```{bash, eval = FALSE}
git clone https://github.com/owid/covid-19-data.git
```
Load the required R Libraries:
```{r}
library(ggplot2)
library(lubridate)
library(plotly)
```


Locate the Canadian Vaccination Data:
```{r}
list.files("../covid-19-data-master/public/data/vaccinations/country_data/")[35]
```

```{r}
list.files("../../canadapopulation/")
```

```{r}
canadaPopulation <- read.csv("../../covid-19-data-master/public/data/vaccinations/country_data/Canada.csv")

```


Read in the csv file:
```{r}
canadaVaccination <- read.csv("../../covid-19-data-master/public/data/vaccinations/country_data/Canada.csv")
```
Convert the data to a data frame:
```{r}
canadaVaccination$date <- as.Date(canadaVaccination$date)
```

The date column will now be in a "date" format:

```{r}
head(canadaVaccination)
```

```{r}
canadaVaccination$date[1]
```


Plot the total vaccinations:
```{r, eval = FALSE}

library(plotly)
canadaVaccination <- read.csv("../../covid-19-data-master/public/data/vaccinations/country_data/Canada.csv")
canadaVaccination$date <- as.Date(canadaVaccination$date)

hline <- function(y = 0, color = "black") {
  list(
    type = "line",
    x0 = 0,
    x1 = 1,
    xref = "paper",
    y0 = y,
    y1 = y,
    line = list(color = color)
  )
}

plot_ly(canadaVaccination, x = ~date, y = ~total_vaccinations, type = 'scatter', mode = 'lines', name = 'Total Doses')%>%
  layout(title = 'Canada: Vaccinations', plot_bgcolor = "#e5ecf6", yaxis = list(title = 'Total Vaccinations'), xaxis = list(title = 'Date'))%>% 
  add_trace(y = ~people_vaccinated, name = 'People Vaccinated \n(1st or 2nd Dose)', mode = 'lines')%>% 
  add_trace(y = ~people_fully_vaccinated, name = 'People Fully Vaccinated \n(1st and 2nd Dose)', mode = 'lines')%>%
  layout(shapes = hline(38131104), plot_bgcolor = "#e5ecf6")%>%
  add_text(showlegend = FALSE, x = c("2021-08-01"), y = c(36131104),
           text = c("Population (38.1M)"))

```
          


